"""init schema

Revision ID: 20260112_init_schema
Revises: 
Create Date: 2026-01-12 17:43:19.366422
"""

from alembic import op
import sqlalchemy as sa



revision = "20260112_init_schema"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Integer(), nullable=True),
    sa.Column('warnings', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('brevo_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('batch_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('payload_redacted', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brevo_logs_id'), 'brevo_logs', ['id'], unique=False)
    op.create_index(op.f('ix_brevo_logs_run_id'), 'brevo_logs', ['run_id'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('template_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_id'), 'campaigns', ['id'], unique=False)
    op.create_table('config_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'key', name='uix_tenant_key')
    )
    op.create_index(op.f('ix_config_settings_id'), 'config_settings', ['id'], unique=False)
    op.create_table('contact_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_code', sa.String(), nullable=False),
    sa.Column('last_contact_at', sa.DateTime(), nullable=True),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('meta', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_history_customer_code'), 'contact_history', ['customer_code'], unique=False)
    op.create_index(op.f('ix_contact_history_id'), 'contact_history', ['id'], unique=False)
    op.create_table('reco_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('dataset_version', sa.String(), nullable=True),
    sa.Column('config_hash', sa.String(), nullable=True),
    sa.Column('code_version', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reco_runs_id'), 'reco_runs', ['id'], unique=False)
    op.create_index(op.f('ix_reco_runs_run_id'), 'reco_runs', ['run_id'], unique=True)
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_code', sa.String(), nullable=True),
    sa.Column('product_key', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('scenario', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_client_code'), 'recommendations', ['client_code'], unique=False)
    op.create_index(op.f('ix_recommendations_id'), 'recommendations', ['id'], unique=False)
    op.create_index(op.f('ix_recommendations_product_key'), 'recommendations', ['product_key'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('audit_output',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('customer_code', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('rule_code', sa.String(), nullable=False),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['reco_runs.run_id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_output_customer_code'), 'audit_output', ['customer_code'], unique=False)
    op.create_index(op.f('ix_audit_output_id'), 'audit_output', ['id'], unique=False)
    op.create_index(op.f('ix_audit_output_run_id'), 'audit_output', ['run_id'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_code', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('last_purchase_date', sa.DateTime(), nullable=True),
    sa.Column('total_spent', sa.Float(), nullable=True),
    sa.Column('total_orders', sa.Integer(), nullable=True),
    sa.Column('average_order_value', sa.Float(), nullable=True),
    sa.Column('recency', sa.Float(), nullable=True),
    sa.Column('frequency', sa.Float(), nullable=True),
    sa.Column('monetary', sa.Float(), nullable=True),
    sa.Column('rfm_score', sa.Integer(), nullable=True),
    sa.Column('rfm_segment', sa.String(), nullable=True),
    sa.Column('preferred_families', sa.Text(), nullable=True),
    sa.Column('budget_band', sa.String(), nullable=True),
    sa.Column('aroma_profile', sa.Text(), nullable=True),
    sa.Column('cluster', sa.String(), nullable=True),
    sa.Column('last_contact_date', sa.DateTime(), nullable=True),
    sa.Column('email_opt_out', sa.Boolean(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_client_code'), 'clients', ['client_code'], unique=False)
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_table('next_action_output',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('customer_code', sa.String(), nullable=False),
    sa.Column('eligible', sa.Boolean(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('scenario', sa.String(), nullable=True),
    sa.Column('audit_score', sa.Float(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['reco_runs.run_id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_next_action_output_customer_code'), 'next_action_output', ['customer_code'], unique=False)
    op.create_index(op.f('ix_next_action_output_id'), 'next_action_output', ['id'], unique=False)
    op.create_index(op.f('ix_next_action_output_run_id'), 'next_action_output', ['run_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_key', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('family_crm', sa.String(), nullable=True),
    sa.Column('sub_family', sa.String(), nullable=True),
    sa.Column('cepage', sa.String(), nullable=True),
    sa.Column('sucrosite_niveau', sa.String(), nullable=True),
    sa.Column('price_ttc', sa.Float(), nullable=True),
    sa.Column('margin', sa.Float(), nullable=True),
    sa.Column('premium_tier', sa.String(), nullable=True),
    sa.Column('price_band', sa.String(), nullable=True),
    sa.Column('aroma_fruit', sa.Float(), nullable=True),
    sa.Column('aroma_floral', sa.Float(), nullable=True),
    sa.Column('aroma_spice', sa.Float(), nullable=True),
    sa.Column('aroma_mineral', sa.Float(), nullable=True),
    sa.Column('aroma_acidity', sa.Float(), nullable=True),
    sa.Column('aroma_body', sa.Float(), nullable=True),
    sa.Column('aroma_tannin', sa.Float(), nullable=True),
    sa.Column('global_popularity_score', sa.Float(), nullable=True),
    sa.Column('season_tags', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_product_key'), 'products', ['product_key'], unique=True)
    op.create_table('reco_output',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('customer_code', sa.String(), nullable=False),
    sa.Column('scenario', sa.String(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('product_key', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('explain_short', sa.String(), nullable=True),
    sa.Column('reasons_json', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['reco_runs.run_id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reco_output_customer_code'), 'reco_output', ['customer_code'], unique=False)
    op.create_index(op.f('ix_reco_output_id'), 'reco_output', ['id'], unique=False)
    op.create_index(op.f('ix_reco_output_run_id'), 'reco_output', ['run_id'], unique=False)
    op.create_table('run_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('summary_json', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['reco_runs.run_id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_index(op.f('ix_run_summary_id'), 'run_summary', ['id'], unique=False)
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=True),
    sa.Column('product_key', sa.String(), nullable=True),
    sa.Column('client_code', sa.String(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('sale_date', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_client_code'), 'sales', ['client_code'], unique=False)
    op.create_index(op.f('ix_sales_document_id'), 'sales', ['document_id'], unique=False)
    op.create_index(op.f('ix_sales_id'), 'sales', ['id'], unique=False)
    op.create_index(op.f('ix_sales_product_key'), 'sales', ['product_key'], unique=False)
    op.create_table('contact_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('contact_date', sa.DateTime(), nullable=True),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_events_id'), 'contact_events', ['id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_table('product_alias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label_raw', sa.String(), nullable=True),
    sa.Column('label_norm', sa.String(), nullable=True),
    sa.Column('product_key', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_key'], ['products.product_key'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'label_norm', name='uq_product_alias_label_tenant')
    )
    op.create_index(op.f('ix_product_alias_id'), 'product_alias', ['id'], unique=False)
    op.create_index(op.f('ix_product_alias_label_norm'), 'product_alias', ['label_norm'], unique=False)
    op.create_table('reco_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('scenario', sa.String(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('explain_short', sa.String(), nullable=True),
    sa.Column('reasons_json', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['reco_runs.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reco_items_id'), 'reco_items', ['id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_reco_items_id'), table_name='reco_items')
    op.drop_table('reco_items')
    op.drop_index(op.f('ix_product_alias_label_norm'), table_name='product_alias')
    op.drop_index(op.f('ix_product_alias_id'), table_name='product_alias')
    op.drop_table('product_alias')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_contact_events_id'), table_name='contact_events')
    op.drop_table('contact_events')
    op.drop_index(op.f('ix_sales_product_key'), table_name='sales')
    op.drop_index(op.f('ix_sales_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_document_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_client_code'), table_name='sales')
    op.drop_table('sales')
    op.drop_index(op.f('ix_run_summary_id'), table_name='run_summary')
    op.drop_table('run_summary')
    op.drop_index(op.f('ix_reco_output_run_id'), table_name='reco_output')
    op.drop_index(op.f('ix_reco_output_id'), table_name='reco_output')
    op.drop_index(op.f('ix_reco_output_customer_code'), table_name='reco_output')
    op.drop_table('reco_output')
    op.drop_index(op.f('ix_products_product_key'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_next_action_output_run_id'), table_name='next_action_output')
    op.drop_index(op.f('ix_next_action_output_id'), table_name='next_action_output')
    op.drop_index(op.f('ix_next_action_output_customer_code'), table_name='next_action_output')
    op.drop_table('next_action_output')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_client_code'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_audit_output_run_id'), table_name='audit_output')
    op.drop_index(op.f('ix_audit_output_id'), table_name='audit_output')
    op.drop_index(op.f('ix_audit_output_customer_code'), table_name='audit_output')
    op.drop_table('audit_output')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_recommendations_product_key'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_client_code'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_reco_runs_run_id'), table_name='reco_runs')
    op.drop_index(op.f('ix_reco_runs_id'), table_name='reco_runs')
    op.drop_table('reco_runs')
    op.drop_index(op.f('ix_contact_history_id'), table_name='contact_history')
    op.drop_index(op.f('ix_contact_history_customer_code'), table_name='contact_history')
    op.drop_table('contact_history')
    op.drop_index(op.f('ix_config_settings_id'), table_name='config_settings')
    op.drop_table('config_settings')
    op.drop_index(op.f('ix_campaigns_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_brevo_logs_run_id'), table_name='brevo_logs')
    op.drop_index(op.f('ix_brevo_logs_id'), table_name='brevo_logs')
    op.drop_table('brevo_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
